Look up default group
Test fails when installing locally (not as "root") if a group named "$user" does not exist on the system:

Error: Couldn't get gid for non-existent group <$user> at /path/to/Daemon/Control.pm line 175.

Solution: Look up gid for $user, then look up group name for gid.